routes/web.php
<?php
use Illuminate\Support\Facades\Cookie;

//!!!!!!!!!!!!!!!!!! PRIORITET !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
//TODO: Event trigger za obican input (mogucnost definisanja da li se dize event na true ili na false) (admin + korisnik)
//TODO: Hendlovanje obicnih inputa u automatizacionim pravilima
//TODO: Ne osvezava settings.json????????????????
//TODO: EVENT za reset uredjaja !!!!!!!!!!!!!!!!!!!!
//TODO: Ne izracunava dobro threshold
//TODO: Monitoring temperature procesora
//*******************************************************************************************************

// TODO: Obratiti pažnju da kada se pojave vezani podaci za korisnika, treba umesto brisanja korisnika bez ikakve provere, samo da se korisnik deaktivira!!!
// TODO: Neophodno je UVEK umesto btn-primary koristiti btn-primary btn-primary-my koji je definisan u public/AdminLTE/build/less/buttons.less!!!

//TODO: Format topica: udi_uredjaja/uui_velicine/vrednost

//TODO: Kako bezbedno generisati i cuvati sifru korisnika za MQTT?

//Kako izvesti samopodesavanje uredjaja?
//1. Prilikom startovanja uredjaja/skripte, salje se poruka getsettings
//2. Node skripta prepoznaje tu poruku i poziva rutu na serveru koja emituje poedsavanja uredjaja u JSON formatu (ova metoda treba da bude zasticena tako da samo sa jedne IP adrese moze biti pozvana)
//3. Uredjaj prihvata emitovane poruke i smesta ih u settings file
//Ista procedura se primenjuje kada korisnik promeni min ili max


//TODO: Mehanizam provere koje su vrednosti prihvacene od strane uredjaja

//Notifikacije i eventi!!!!!!!!!!!!!!!!!!!
//Event se kreira iz putem odredjene rute
//Event ima vek trajanja 1 sat i ne mogu biti kreirana 2 eventa istog tipa u tom razdoblju
//Svi eventi koji nisu updejtovani vise od 2 sata (120 minuta) vremena obelezavaju se kao neaktivni
//Vreme trajanja eventa je definisano u config/inputevents

//TODO: Kako biti siguran da je uredjaj primio poruku da nesto uradi? Kako obavestiti korisnika da uredjaj nije primio poruku? Da li vrsiti proveru dostupnosti uredjaja pre samog slanja?

//TODO: Rasporedjivanje elemenata po zelji korisnika

//TODO: Dodati push button (podesavanje vremena trajanja impulsa)



//TODO: Detaljne statistike

//TODO: IF this than that logika (razmisli kako resiti problem vremenskih rasporeda, npr. ukljuci samo posle 18h)
//Uvesti dve vrste: 1. regular, 2. roaming
//1. Regular: omogucava programiranje ulaza i izlaza samo u okviru jednog uredjaja
//2. Roaming: omogucava interakciju ulaza i izlaza u okviru svih uredjaja datog korisnika
//Roaming se obavlja posredstvom servera uz proveru da li uredjaji pripadaju istom korisniku
//Roaming je dostupan samo odredjenim korisnickim paketima
//Za pocetak implemetirati najednostavniju interakciju izlaza i ulaza + vremensko programiranje
//Kombinovanje vise uslova pomocu operatora (AND, OR, XOR)
//Mogucnost dodavanja vise izlaznih vrednosti za jedno IFTTT pravilo
//Mogucnost sagledavanja prosecnih vrednosti vise senzora
//Dodati mogucnost odabira odstupanja vrednosti za svaki uslov/pravilo (0-5%)


//Obavestavanje korisnika (sms, e-mail, push-notifikacije)

//TODO: Mobilna aplikacija

//HARDVERSKI DEO******************************************

//TODO: Prekidac za rucni mod upravljanja koji ce omoguciti upravljanje cak iako softver pukne

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/phpinfo',function(){
    phpinfo();
});*/

Route::get('/','WelcomeController@index')->name('home');

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::get('setlocale/{locale}', function ($locale) {

    $cookie=Cookie::forever('locale', $locale);

    return redirect('/')->withCookie($cookie);
});
//***************************USERS********************************************************************************************
Route::get('/users', 'KorisniciController@index')->name('users.all');
Route::get('/users/delete/{id}', 'KorisniciController@delete')->name("users.delete");
Route::get('/users/edit/{id}', 'KorisniciController@edit')->name("users.edit");
Route::patch('/users/update/{id}', 'KorisniciController@update')->name("users.update");
Route::get('/users/activatedeactivate/{id}', 'KorisniciController@activatedeactivate')->name("users.activatedeactivate");

Route::get('/users/credentials/changepassword','KorisniciController@credentials')->name('users.credentials');
Route::post('/users/credentials/changepassword','KorisniciController@postCredentials')->name('users.credentials.changepassword');

//***************************END USERS********************************************************************************************


//***************************MQTT LOGS********************************************************************************************

Route::get('/mqttlogs', 'MqttLogsController@index')->name('mqttlogs.all');
Route::get('/mqttlogs/get/{last?}', 'MqttLogsController@get')->name('mqttlogs.get');

//***************************END MQTT LOGS********************************************************************************************


//***************************DEVICES********************************************************************************************

Route::get('/devices', 'DevicesController@index')->name('devices.all');
Route::get('/devices/get/{last?}', 'DevicesController@get')->name('devices.get');

Route::get('/devices/add', 'DevicesController@add')->name('devices.add');
Route::post('/devices/add', 'DevicesController@create')->name('devices.create');

Route::get('/devices/delete/{id}', 'DevicesController@delete')->name('devices.delete');

Route::get('/devices/edit/{id}', 'DevicesController@edit')->name("devices.edit");
Route::patch('/devices/update/{id}', 'DevicesController@update')->name("devices.update");

Route::get('/devices/setup/{id}', 'DevicesController@setup')->name('devices.setup');

//This is used to allow users to change device name, output name and background color
Route::get('/devices/customize/{id}', 'DevicesCustomizeController@customize')->name("devices.customize");
Route::patch('/devices/customize/{id}', 'DevicesCustomizeController@customizePost')->name("devices.customizePost");

Route::get('/devices/customize/showhide/{type}/{id}/{state}','DevicesCustomizeController@showhide');
//***************************END DEVICES********************************************************************************************


//***************************MQTT PUBLISH********************************************************************************************

Route::get('/mqtt/publish/{device_id}/{output_id?}/{message}', 'MqttPublisherController@publish')->name('mqttlogs.publish');

Route::get('/mqtt/getsettings/{device_id}', 'MqttPublishSettingsController@publishSettings');

Route::post('/mqtt/inputevent/{uui}', 'MqttPublishSettingsController@createEvent');

//***************************END MQTT PUBLISH********************************************************************************************


//***************************A U T O M A T I O N********************************************************************************************

Route::get('/automation', 'AutomationController@index')->name('automation.all');

Route::get('/automation/get/{option?}', 'AutomationController@get');

Route::get('/automation/logicaloperatorsdropdown','AutomationController@logicaloperatorsdropdown');

Route::get('/automation/conditiontypesdropdown','AutomationController@conditiontypesdropdown');

Route::get('/automation/inputsdropdown/{device_id}','AutomationController@inputsdropdown');

Route::get('/automation/outputsdropdown/{device_id}','AutomationController@outputsdropdown');

Route::get('/automation/comparisonoperatorsdropdown','AutomationController@comparisonoperatorsdropdown');

Route::get('/automation/add', 'AutomationController@add')->name('automation.add');
Route::post('/automation/add', 'AutomationController@create')->name('automation.create');

Route::get('/automation/edit/{id}', 'AutomationController@edit')->name('automation.edit');
Route::patch('/automation/edit/{id}', 'AutomationController@update')->name('automation.update');

Route::get('/automation/delete/{id}', 'AutomationController@delete');

Route::get('/automation/disableall/{output_id}', 'AutomationController@disableall');
//***************************E N D    A U T O M A T I O N********************************************************************************************


//***************************E V E N T S********************************************************************************************

Route::get('/events', 'EventController@index')->name('events.all');

Route::get('/events/get/{option}', 'EventController@get');

Route::get('/events/inputevent/{device_id}/{uui}/{message}', 'CreateEventController@createEvent');

//***************************E N D    E V E N T S********************************************************************************************


//***************************HISTORY********************************************************************************************

Route::get('/history/output/{id}', 'HistoryController@output')->name('history.output');

Route::get('/history/input/{id}', 'HistoryController@input')->name('history.input');

Route::get('/history/digitalinput/{id}', 'HistoryController@digitalinput')->name('history.digitalinput');

//***************************END HISTORY********************************************************************************************


//Route::get('/test/{user_id}','MqttPublisherController@publishRules');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Notifications\MyResetPassword;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;
use OwenIt\Auditing\Contracts\UserResolver;


class User extends Authenticatable implements AuditableContract, UserResolver
{
    use Auditable;
    use Notifiable;
    use SoftDeletes;

    protected $auditThreshold = 100;

    public static function resolveId()
    {
        return Auth::check() ? Auth::user()->getAuthIdentifier() : null;
    }
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'subscription_id', 'name', 'email', 'password', 'surname', 'streetandnumber', 'postalcode', 'city', 'country', 'phonenumber', 'role', 'isActive', 'mqtt_super', 'pw', 'locale'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    protected $hidden = [
        'password', 'remember_token',
    ];


    public function acl()
    {
        return $this->hasMany('App\Acl', 'email', 'email');
    }

    public function device()
    {
        return $this->hasMany('App\Device');
    }

    public function rule()
    {
        return $this->hasMany('App\Rule');
    }
    
    public function subscription(){
        return $this->belongsTo('App\Subscription');
    }

    public function getFullnameAttribute()
    {
        return $this->name . ' ' . $this->surname;
    }

    public function getFullnameEmailAttribute()
    {
        return $this->name . ' ' . $this->surname . ' - ' . $this->email;
    }

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new MyResetPassword($token));
    }

}

resources/views/template/footer.blade.php
<!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right
    <div class="pull-right hidden-xs">
        Anything you want
    </div>-->
    <!-- Default to the left -->
    <strong>Copyright &copy; 2017 <a href="#">Company</a>.</strong> {{ trans('messages.allRightsReserved') }}
</footer>

resources/views/template/header.blade.php
<!-- Main Header -->
<header class="main-header">

    <!-- Logo -->
    <a href="{{url('/')}}" class="logo">

        <span class="logo-mini">
            <!-- <b>N</b>T -->
            <!-- The logo image in the navbar-->
            <img src="{{ asset("/img/logo.png") }}" class="logo-image" alt="Logo Image" style="max-width: 40px;"/>
        </span>
        <span class="logo-lg">
            <!-- The logo image in the navbar-->
            <img src="{{ asset("/img/logo.png") }}" class="logo-image" alt="Logo Image" style="max-width: 40px;"/>
            <b>&nbsp;AGRO </b>TASKS
        </span>

    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- Messages: style can be found in dropdown.less-->

                <!-- /.messages-menu -->

                <li class="dropdown tasks-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-flag-o"></i>
                        <span class="label label-danger">{{Cookie::get('locale')}}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">{{trans('messages.chooseLanguage')}}:</li>
                        <li>
                            <!-- Inner menu: contains the tasks -->
                            <ul class="menu">
                                <li><!-- Task item -->
                                    <a href="{{url('/setlocale/de')}}">
                                        <!-- Task title and progress text -->
                                        <h3>
                                            {{trans('messages.deutsch')}}
                                        </h3>
                                        <!-- The progress bar -->
                                    </a>
                                </li>
                                <!-- end task item -->
                                <li><!-- Task item -->
                                    <a href="{{url('/setlocale/sr')}}">
                                        <!-- Task title and progress text -->
                                        <h3>
                                            {{trans('messages.serbian')}}
                                        </h3>
                                        <!-- The progress bar -->
                                    </a>
                                </li>
                                <li><!-- Task item -->
                                    <a href="{{url('/setlocale/en')}}">
                                        <!-- Task title and progress text -->
                                        <h3>
                                            {{trans('messages.english')}}
                                        </h3>
                                        <!-- The progress bar -->
                                    </a>
                                </li>
                                <!-- end task item -->
                            </ul>
                        </li>

                    </ul>
                </li>

                {{--<li class="dropdown messages-menu">
                    <!-- Menu toggle button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-envelope-o"></i>
                        <span class="label label-success">4</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 4 messages</li>
                        <li>
                            <!-- inner menu: contains the messages -->
                            <ul class="menu">
                                <li><!-- start message -->
                                    <a href="#">
                                        <div class="pull-left">
                                            <!-- User Image -->
                                            <img src="{{  asset("/AdminLTE/dist/img/user2-160x160.jpg") }}"
                                                 class="img-circle" alt="User Image">
                                        </div>
                                        <!-- Message title and timestamp -->
                                        <h4>
                                            Support Team
                                            <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                        </h4>
                                        <!-- The message -->
                                        <p>Why not buy a new awesome theme?</p>
                                    </a>
                                </li>
                                <!-- end message -->
                            </ul>
                            <!-- /.menu -->
                        </li>
                        <li class="footer"><a href="#">See All Messages</a></li>
                    </ul>
                </li>
                <!-- /.messages-menu -->

                <!-- Notifications Menu -->
                <li class="dropdown notifications-menu">
                    <!-- Menu toggle button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell-o"></i>
                        <span class="label label-warning">10</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 10 notifications</li>
                        <li>
                            <!-- Inner Menu: contains the notifications -->
                            <ul class="menu">
                                <li><!-- start notification -->
                                    <a href="#">
                                        <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                    </a>
                                </li>
                                <!-- end notification -->
                            </ul>
                        </li>
                        <li class="footer"><a href="#">View all</a></li>
                    </ul>
                </li>
                <!-- Tasks Menu -->
                <li class="dropdown tasks-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-flag-o"></i>
                        <span class="label label-danger">9</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 9 tasks</li>
                        <li>
                            <!-- Inner menu: contains the tasks -->
                            <ul class="menu">
                                <li><!-- Task item -->
                                    <a href="#">
                                        <!-- Task title and progress text -->
                                        <h3>
                                            Design some buttons
                                            <small class="pull-right">20%</small>
                                        </h3>
                                        <!-- The progress bar -->
                                        <div class="progress xs">
                                            <!-- Change the css width attribute to simulate progress -->
                                            <div class="progress-bar progress-bar-aqua" style="width: 20%"
                                                 role="progressbar" aria-valuenow="20" aria-valuemin="0"
                                                 aria-valuemax="100">
                                                <span class="sr-only">20% Complete</span>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <!-- end task item -->
                            </ul>
                        </li>
                        <li class="footer">
                            <a href="#">View all tasks</a>
                        </li>
                    </ul>
                </li>--}}
                <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        <img src="{{  asset("AdminLTE/dist/img/user2-160x160.jpg") }}" class="user-image"
                             alt="User Image">
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">{{ Auth::user()->fullname }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src={{  asset("AdminLTE/dist/img/user2-160x160.jpg") }} class="img-circle"
                                 alt="User Image">

                            <p>
                                {{ Auth::user()->fullname }}
                                <small>{{ Helper::roleToString(Auth::user()->role) }}&nbsp;({{Auth::user()->subscription->name}})</small>

                            </p>
                        </li>
                        {{--<!-- Menu Body -->
                        <li class="user-body">
                            <div class="row">
                                <div class="col-xs-4 text-center">
                                    <a href="#">Followers</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Sales</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Friends</a>
                                </div>
                            </div>
                            <!-- /.row -->
                        </li>--}}
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{{route('users.credentials')}}" class="btn btn-default btn-flat">{{ trans('messages.btnProfile') }}</a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ url('/logout') }}"
                                   onclick="event.preventDefault(); document.getElementById('logout-form').submit();"
                                   class="btn btn-default btn-flat">{{trans('messages.logOut')}}</a>
                                <form id="logout-form" action="{{ url('/logout') }}" method="POST"
                                      style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/template/sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <br>
        <!-- Sidebar Menu -->
        <ul class="sidebar-menu">
            <li class="header">{{ trans('messages.menuTitle') }}</li>

            <!-- Optionally, you can add icons to the links -->
            @if(Auth::user()->role == 'admin')
                <li class="{{ Request::is('users*') ? 'active' : '' }}"><a href="{{route('users.all')}}"><i
                                class="fa fa-users"></i> <span>{{ trans('messages.users') }}</span></a></li>

                <li class="{{ Request::is('devices*') ? 'active' : '' }}"><a href="{{route('devices.all')}}"><i
                                class="fa fa-laptop"></i> <span>{{ trans('messages.menuDevices') }}</span></a></li>

                <li class="{{ Request::is('mqttlogs*') ? 'active' : '' }}"><a href="{{route('mqttlogs.all')}}"><i
                                class="fa fa-list"></i> <span>{{ trans('messages.menuMQTTLogs') }}</span></a></li>
            @endif

            @if(Auth::user()->role == 'user')
                <li class="{{ Request::is('automation*') ? 'active' : '' }}"><a href="{{route('automation.all')}}"><i
                                class="fa fa-magic"></i> <span>{{ trans('messages.automation') }}</span></a>
                </li>

                <?php
                $dids = \App\Device::where('user_id', Auth::id())->get(['id']);
                $di = [];
                foreach ($dids as $d) {
                    array_push($di, $d['id']);
                }
                $inputs = \App\Input::whereIn('device_id', $di)->count();
                ?>
                @if($inputs>0)
                    <li class="{{ Request::is('events*') ? 'active' : '' }}"><a href="{{route('events.all')}}"><i
                                    class="fa fa-exclamation-triangle"></i> <span>{{ trans('messages.events') }}</span></a>
                    </li>
                @endif
            @endif

            {{--<li><a href="#"><i class="fa fa-link"></i> <span>Another Link</span></a></li>
            <li class="treeview">
                <a href="#"><i class="fa fa-link"></i> <span>Multilevel</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#">Link in level 2</a></li>
                    <li><a href="#">Link in level 2</a></li>
                </ul>
            </li>--}}
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>